### ISSUE TITLE
Labels for classifications

### ISSUE THREAD

**Issue by xilinxJAM** [hirayaku/DAC2018-TGIIF#1]
Hi Hirayaku,
Can you also supply a file mapping just the classification ID to the dataset label.
I don't think the main data set is available, so I cant get access these yet.
![image](https://user-images.githubusercontent.com/42800600/44776766-c08db780-ab70-11e8-8b62-6cd791290b11.png)

**Comment by sl-zeng** [comment]
Hi jamjamx,

The file you need is uploaded in /model directory. 

Best Regards!
