### ISSUE TITLE
dpu_initialize error

### ISSUE THREAD

**Issue by shinya321** [hirayaku/DAC2018-TGIIF#2]
Thank u for your great work!!
I am really interested in your SSD working on PYNQ board.
After building the environment following your README, step by step I execute your 'TGIIF.ipynb',
but I met an error as below:

<pre>
> dpu_lib.dpu_initialize(c_lib_path)
DPU InputSize : 338688
DPU OutputSize: 1058904
- - - - - - - - - -
Illegal instruction
</pre>

Where's wrong ?
Sorry to be poor English, it would be greatly appreciated if you could explain the details.

Best regards

**Comment by sl-zeng** [comment]
Hi shinya321,

Could you please run the cmd below and show the print info?
```
cat /proc/dpu_info
```
It seems that dnndk package is not properly installed.

Thanks!

**Comment by shiyangcool** [comment]
Hi，thanks for  your great work，when i use your tcl to build a vivado project，have a error，say that not have Deephi ip，can your tell me，how could i creat a project of vivado that use your pynq_dpu_142m.tcl


Best regards

**Comment by sl-zeng** [comment]
Hi shiyangcool,

Since the DPU RTL IP is of DeePhi(Now part of Xilinx), I am afraid that you could only test our design with the bitstream right now. 

To access the evaluation of DeePhi DPU IP, please refer to the dnndk@deephi.tech for further assistance.

Best Regards!

**Comment by shinya321** [comment]
Hi sl-zeng.
Thank you for replying me!!
Sorry, I met another problem as below:
<pre>
setenv bootargs 'console=ttyPS0,115200 mem=256M root=/dev/mmcblk0p2 rw earlyprintk rootfstype=ext4 rootwait devtmpfs.mount=1 >uio_pdrv_genirq.of_id="generic-uio"'
setenv fdt_high 0x10000000
setenv initrd_high 0x10000000
saveenv
pri
-bash: pri: command not found
</pre>

What is "pri" command?
it would be greatly appreciated if you could explain the details.

Best regards

**Comment by sl-zeng** [comment]
> Hi sl-zeng.
> Thank you for replying me!!
> Sorry, I met another problem as below:
> 
> setenv bootargs 'console=ttyPS0,115200 mem=256M root=/dev/mmcblk0p2 rw earlyprintk rootfstype=ext4 rootwait devtmpfs.mount=1 >uio_pdrv_genirq.of_id="generic-uio"'
> setenv fdt_high 0x10000000
> setenv initrd_high 0x10000000
> saveenv
> pri
> -bash: pri: command not found
> What is "pri" command?
> it would be greatly appreciated if you could explain the details.
> 
> Best regards

It is a command that will print all the infos about the boot stage. Just to make sure that the bootargs have been successfully set up. It's okay to skip this command.

Best Regards

**Comment by shinya321** [comment]
Hi sl-zeng.
Thank you for replying me!!
Sorry for asking again & again, but I have another question...

---

**Question1**:
As README in prerequisites, I need to "`Stop the autostart at the booting stage, and then type the cmds`",
but how to do that??
Here is autostart service I check :
<pre>
$ systemctl list-unit-files | grep enable
autovt@.service                            enabled
binfmt-support.service                     enabled
boot_leds.service                          enabled
cron.service                               enabled
fake-hwclock.service                       enabled
getty@.service                             enabled
jupyter.service                            enabled
networking.service                         enabled
pl_server.service                          enabled
resizefs.service                           enabled
resolvconf.service                         enabled
rsyslog.service                            enabled
ssh.service                                enabled
sshd.service                               enabled
syslog.service                             enabled
systemd-timesyncd.service                  enabled
unattended-upgrades.service                enabled
wifi_connect.service                       enabled
remote-fs.target                           enabled
apt-daily.timer                            enabled
</pre>

---

**Question2**:
Also as README in prerequisites, I need to type `setenv / saveenv` cmd, 
but there are no `csh/tcsh` in pynq_z1 v2.1 image file.
So do I need to install csh to PYNQ?

it would be greatly appreciated if you could explain the details.
Best Regards

**Comment by hirayaku** [comment]
Hi shinya,

The step we mention about in the `prerequisites/README.md` should be done when the board is **booting**, before the linux kernel is up and running.
Say you have linux up already and you are in a bash environment, please reboot your board (reset the board, reboot cmd or whatever). When the board is booting, keep your terminal connected to the board via serial port, you will see the message:
**Hit any key to stop autoboot**
Please do so to stop it, and then you will have a shell beginning with ">Zynq". All the following commands should be exec in this environment.
Don't forget to put the devicetree.dtb in your SD card, though.

Best,
hirayaku
