### ISSUE TITLE
No detection after changing BATCH_SIZE = 5 to 1

### ISSUE THREAD

**Issue by shinya321** [hirayaku/DAC2018-TGIIF#4]
Hi,
I know in your sample code `BATCH_SIZE = 5` as default. 
But I wanna input only one image into SSD network,
so I changed BATCH_SIZE from 5 to 1 in preprocessing.py.
After doing so I executed SSD, there were no error.
but there were no detections in XML file, although it did work well 
when BATCH_SIZE =5.
The result example is below:

**BATCH_SIZE = 5:**
```
<?xml version="1.0" encoding="utf-8"?>
	<annotation>
		<filename>0.jpg</filename>
		<size>
			<width>640</width>
			<length>360</length>
		</size>
		<object>
			<name>NotCare</name>
			<bndbox>
				<xmin>56</xmin>
				<xmax>947</xmax>
				<ymin>0</ymin>
				<ymax>1080</ymax>
			</bndbox>
		</object>
	</annotation>
```

**BATCH_SIZE = 1:**
```
<?xml version="1.0" encoding="utf-8"?>
	<annotation>
		<filename>0.jpg</filename>
		<size>
			<width>640</width>
			<length>360</length>
		</size>
		<object>
			<name>NotCare</name>
			<bndbox>
				<xmin>0</xmin>
				<xmax>0</xmax>
				<ymin>0</ymin>
				<ymax>0</ymax>
			</bndbox>
		</object>
	</annotation>
```

How do I input only one image at once??
If you have any comment, could you please how to do??

Best regards,
shinya321

**Comment by hirayaku** [comment]
Hi shinya,

To detect the image one by one, please use `dpu_detect_single` function. We have no plan to make `dpu_detect_list` to support single image detection.

You could find the function definitions from `src/main.cpp`:488  to `src/main.cpp`:533. For `dpu_detect_single`, it accepts the path of the single picture as the only argument. For `dpu_detect_list`, it accepts the path of the file which has a list of pictures to detect as the 1st arg, and the number of imgs as the 2nd arg. **We are actually calling these C functions in our ipython notebook.** Refer to the other sections of the ipython notebook for how to pass the argument to these functions via CFFI in python.

Also, to use `dpu_detect_single`, you need to slightly modify the ipython notebook, e.g. acquiring the image names from `batch` one by one and feeding them to `dpu_detect_single`.

Feel free to ask if you have any further questions.
hirayaku
