### ISSUE TITLE
I am wondering if the project support my ultra96 boards with PYNQ-image-v2.3?

### ISSUE THREAD

**Issue by cssxiaoxiao** [hirayaku/DAC2018-TGIIF#5]
I am wondering if the project support my ultra96 boards with PYNQ-image-v2.3?

**Comment by sl-zeng** [comment]
Hi xssxiaoxiao,

The bitstream file is related to the board, which is PYNQ-Z1 right now. I am afraid that you have to wait until the release of the DPU IP on the DeePhi website to have your own project on ultra96 boards.

Thanks!
